### ISSUE TITLE
Spelling mistake in week 2 blogpost

### ISSUE THREAD

**Issue by mxmsunny** [hunter-college-ossd-spr19/Chocolate-Spaghet-weekly#1]
In the paragraph starting with, "Something I have to...," the word, "usefull"(line 3), is spelled incorrectly. <br />
In the last paragraph, the word, "successfull"(4th line from the bottom), is spelled incorrectly.

**Comment by Chocolate-Spaghet** [comment]
Thank you for bringing this to my attention!
