### ISSUE TITLE
Grammar and Spelling in Week 1 Blog Post

### ISSUE THREAD

**Issue by johncgenere** [hunter-college-ossd-spr19/Chocolate-Spaghet-weekly#2]
This issue is in regards to this blog post: https://hunter-college-ossd-spr19.github.io/Chocolate-Spaghet-weekly/week01/

There are a few grammar and spelling errors, it should be a quick fix. I will list them all below:

In the opening sentence:
-  "difintions" is misspelled. This should be changed to "definitions"

In the first full paragraph:
- "The main differences between the two definitions **is** that there’s a different..." should be "The main differences between the two definitions **are** that there’s a different..."
- "a more **agressive** color, commonly" should be "a more **aggressive** color, commonly"
- "While the “Open Source” definition is more of rules to the licenses attached to the software rather than **guidlines** from" should be "While the “Open Source” definition is more of rules to the licenses attached to the software rather than **guidelines** from"
- "**Second** largest difference is that the “Open Source Initiative” declares that companies should be able to use the software, which is also something most of the **poeple** don’t think about when they are talking about Libre Software." should be "**The second** largest difference is that the “Open Source Initiative” declares that companies should be able to use the software, which is also something most of the **people** don’t think about when they are talking about Libre Software."

In the second full paragraph:
- The word "being" was repeated twice before the word "Free Software"

In the small paragraph after the second full paragraph:
- "The Open Source Initiative makes **and** effort to define actual..." should be "The Open Source Initiative makes **an** effort to define actual..."

In the last paragraph:
- "It has all of the **pontential** of being the best map" should be "It has all of the **potential** of being the best map"
- "Either way, this is one of my favorite open source projects and I look forward to **contribute** more to the project." should be "Either way, this is one of my favorite open source projects and I look forward to **contributing** more to the project."

**Comment by Chocolate-Spaghet** [comment]
Thank you for bringing this to my attention!
