### ISSUE TITLE
Spelling and grammar on second weekly post

### ISSUE THREAD

**Issue by DanielSegarra36** [hunter-college-ossd-spr19/Chocolate-Spaghet-weekly#3]
[Week 2 Post: Line 14](https://github.com/hunter-college-ossd-spr19/Chocolate-Spaghet-weekly/commit/d20e8cc12ac059fe4b6f1c85dbeb154dc27a8992#diff-7129bdaf5da2c2cd7dce8d348b57d574R14)
> "... an open source driver CKB for Corsair periferals for Linux and Mac OS operating systems."  

Should be changed to:
"... an open source driver, CKB, for Corsair peripherals on Linux and Mac OS operating systems."

**Comment by Chocolate-Spaghet** [comment]
Thank you for bringing this to my attention!
