### ISSUE TITLE
Spelling Error "prevous" --> "previous"

### ISSUE THREAD

**Issue by emmacromeo** [hunter-college-ossd-spr19/Chocolate-Spaghet-weekly#4]
In your [week 8 blog post](https://github.com/hunter-college-ossd-spr19/Chocolate-Spaghet-weekly/blob/gh-pages/_posts/2019-03-22-week08.md) you have a small spelling mistake.

**Comment by Chocolate-Spaghet** [comment]
Thank you for your contributions! 🎉
